name: Build, test, and doc update
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ['4.10.0']
    - run: opam pin . --with-doc --with_test -yes
    - run: echo '::set-env name=opam-build-root::'`opam config var yuujinchou:build`
      if: ${{ github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && startsWith (github.head_ref, 'doc')) }}
    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && startsWith (github.head_ref, 'doc')) }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ format('{0}/_build/default/_doc/_html/', env.opam-build-root) }}
