name: Build, test, and doc update
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run:
    if: ${{ github.ref == 'refs/heads/master' || (github.event_name == 'pull_request' && startsWith (github.head_ref, 'doc')) }}
    runs-on: ubuntu-latest
    env:
      ocaml-version: '4.10.0'
      opam-status-filepath: './opam-status-for-github-cache.lock'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.opam
        key: ${{ runner.os }}-${{ env.ocaml-version }}-${{ hashFiles(env.opam-status-filepath) }}
        restore-keys:
          ${{ runner.os }}-${{ env.ocaml-version }}-
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ env.ocaml-version }}
    - run: opam upgrade -y
    - run: opam pin . --with-test --with-doc -y
    - run: echo '::set-env name=opam-build-root::'`opam config var yuujinchou:build`
    - run: opam switch export ${{ env.opam-status-filepath }}
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ format('{0}/_build/default/_doc/_html/', env.opam-build-root) }}
