name: Build and test
on: [push,pull_request]
jobs:
  run:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        ocaml-version: ['4.10.0']
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin . --with-test -y
